{
    imports = [
        ./allow.nix
        ./audio.nix
        ./bluetooth.nix
        ./bootloader.nix
        ./display.nix
        ./environment.nix
        ./flakes.nix
        ./gc.nix
        ./keymap.nix
        ./locale.nix
        ./network.nix
        ./package.nix
        ./printScan.nix
        ./system.nix
        ./timezone.nix
        ./user.nix
        ./zram.nix
    ];
}
